import Head from "next/head";
import { Montserrat } from "@next/font/google";
import {
  Box,
  Button,
  Card,
  CardContent,
  CardHeader,
  Container,
  CssBaseline,
  Grid,
  List,
  ListItem,
  ListItemText,
  Stack,
  ThemeProvider,
  Typography,
} from "@mui/material";
import { Header } from "../components";
import { theme } from "../theme";
import "@fontsource/montserrat/400.css";
import "@fontsource/montserrat/500.css";
import "@fontsource/montserrat/600.css";
import "@fontsource/montserrat/700.css";

import "@fontsource/literata/400.css";
import "@fontsource/literata/500.css";
import "@fontsource/literata/600.css";
import "@fontsource/literata/700.css";
import AboutUs from "../sections/AboutUs";
import Vision from "../sections/Vision";
import HomePage from "../sections/HomePage";
import IndivisualGrowth from "../sections/IndivisualGrowth";
import Mission from "../sections/Mission";

const inter = Montserrat({ subsets: ["latin"] });

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Header />
      <Stack gap={20}>
        <HomePage />
        <Container>
          <Stack gap={20}>
            <Vision />
            <AboutUs />
          </Stack>
        </Container>
        <Mission />
        <Container>
          <Stack gap={20}>
            <IndivisualGrowth />
            <div></div>
          </Stack>
        </Container>
      </Stack>
    </ThemeProvider>
  );
}
